import Head from "next/head";
import Navbar from "../components/Navbar";
import HeroPage from "../pages/heroPage";
import Clients from "./clients";
import Services from "./services";
import News from "./news";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive Agency website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />
      <HeroPage />
      <Clients />
      <Services />
      <News />
      <Contact />
      <Footer />
    </div>
  );
}
